In [14]:
from seqclass import DNABertForSequenceClassification
from transformers import BertTokenizer
import json
import os

pretrained_path = os.path.join("..", "pretrained", "3-new-12w-0")
model = DNABertForSequenceClassification.from_pretrained(
    pretrained_path,
    num_labels = 3
)
tokenizer = BertTokenizer.from_pretrained(pretrained_path)
input_tokens = "AAA AAG AGA GAC ACT CTA TAG"
encoded = tokenizer.encode_plus(input_tokens, return_tensors="pt")
input_ids = encoded.get("input_ids")
attention_mask = encoded.get("attention_mask")
print(input_ids, attention_mask)

output = model(input_ids, attention_mask)
print(output.logits)



Some weights of the model checkpoint at ..\pretrained\3-new-12w-0 were not used when initializing DNABertForSequenceClassification: ['cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight']
- This IS expected if you are initializing DNABertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DNABertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DNABertForSequenceClassification were not initialized from the model checkpoint at ..\pret

tensor([[ 2,  5,  8, 17, 55, 14, 41, 24,  3]]) tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 0.0109, -0.1443, -0.3833]], grad_fn=<AddmmBackward0>)


In [1]:
from transformers import BertTokenizer
import os
from models.seqlab import DNABertForTokenClassification
from utils.seqlab import label2id, id2label
import torch

pretrained_path = os.path.join("pretrained", "3-new-12w-0")
model = DNABertForTokenClassification.from_pretrained(
    pretrained_path,
    num_labels = 8,
    id2label = id2label,
    label2id = label2id,
    output_hidden_states = True,
    output_attentions = True)

tokenizer = BertTokenizer.from_pretrained(pretrained_path)
input_tokens = "AAA AAG AGA GAC ACT CTA TAG"
labels = torch.tensor([-100, 0, 0, 4, 2, 3, 6, 7, -100])
encoded = tokenizer.encode_plus(input_tokens, return_tensors="pt")
input_ids = encoded.get("input_ids")
attention_mask = encoded.get("attention_mask")

output = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
output.loss.backward()

Some weights of the model checkpoint at pretrained\3-new-12w-0 were not used when initializing DNABertForTokenClassification: ['cls.predictions.decoder.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias']
- This IS expected if you are initializing DNABertForTokenClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DNABertForTokenClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of DNABertForTokenClassification were not initialized from the model checkpoint at pretrained\3-new-12w-0

In [24]:
import torch
a = torch.randn(5, 2, 3)
print(a)
print(torch.argmax(a, 2).shape)
print(torch.argmax(a, 2).view(-1))
softmax = torch.nn.Softmax(2)
a_softmax = softmax(a)
print(a_softmax)
print(torch.argmax(a_softmax, 2).shape)
print(torch.argmax(a_softmax, 2).view(-1))

tensor([[[-0.5822,  0.0397,  0.5947],
         [-0.6133, -0.3895,  0.4082]],

        [[ 1.9722,  0.8546,  0.6370],
         [ 0.9444,  0.9289,  1.4358]],

        [[ 0.2974, -0.8921,  0.5509],
         [-1.4582, -0.0312,  0.6434]],

        [[ 0.8788, -1.0179, -0.4394],
         [-0.3536, -1.2244,  0.2192]],

        [[-0.2136, -0.7131, -0.7721],
         [-0.2241, -3.6508, -0.0841]]])
torch.Size([5, 2])
tensor([2, 2, 0, 2, 2, 2, 0, 2, 0, 2])
tensor([[[0.1638, 0.3050, 0.5313],
         [0.1989, 0.2488, 0.5523]],

        [[0.6289, 0.2057, 0.1655],
         [0.2763, 0.2721, 0.4517]],

        [[0.3857, 0.1174, 0.4969],
         [0.0749, 0.3122, 0.6129]],

        [[0.7054, 0.1059, 0.1888],
         [0.3133, 0.1312, 0.5555]],

        [[0.4590, 0.2785, 0.2625],
         [0.4581, 0.0149, 0.5270]]])
torch.Size([5, 2])
tensor([2, 2, 0, 2, 2, 2, 0, 2, 0, 2])


In [6]:
import torch

y_pred = []
for i in range(5):
    y_pred.append(
        [1, 2, 3, 4, 5,]
    )

print(y_pred)
y_pred = torch.flatten(torch.tensor(y_pred))

y_target = []
for i in range(5):
    y_target.append(
        [1, 3, 4, 2, 5,]
    )

print(y_target)
y_target = torch.flatten(torch.tensor(y_target))

from utils.metrics import Metrics

y_pred = y_pred.tolist()
y_target = y_target.tolist()
print(y_pred)
print(y_target)
m = Metrics(y_pred, y_target, num_classes=6)
m.calculate()
print(m.precision(0), m.precision(1), m.precision(2), m.precision(3), m.precision(4))
print(m.recall(0), m.recall(1), m.recall(2), m.recall(3), m.recall(4))
print(m.f1_score(0), m.f1_score(1), m.f1_score(2), m.f1_score(3), m.f1_score(4))
m.print_cf()



[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]
[[1, 3, 4, 2, 5], [1, 3, 4, 2, 5], [1, 3, 4, 2, 5], [1, 3, 4, 2, 5], [1, 3, 4, 2, 5]]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 3, 4, 2, 5, 1, 3, 4, 2, 5, 1, 3, 4, 2, 5, 1, 3, 4, 2, 5, 1, 3, 4, 2, 5]
0 1.0 0.0 0.0 0.0
0 1.0 0.0 0.0 0.0
0 1.0 0 0 0
[0 0 0 0 0 0]
[0 5 0 0 0 0]
[0 0 0 0 5 0]
[0 0 5 0 0 0]
[0 0 0 5 0 0]
[0 0 0 0 0 5]
