In [2]:
"""
Check if CUDA is supported.
"""
import torch
torch.cuda.is_available()
torch.device('cuda:0')
torch.cuda.get_device_name(0)
_device = torch.device('cuda:0')


In [3]:
import pandas as pd
from data_preparation import kmer

def get_sequences(csv_path, n_sample=10, random_state=1337):
    r"""
    Get sequence from certain CSV. CSV has header such as 'sequence', 'label_prom', 'label_ss', 'label_polya'.
    """
    df = pd.read_csv(csv_path)
    if (n_sample > 0):
        df = df.sample(n=n_sample, random_state=random_state)
    sequence = list(df['sequence'])
    label_prom = list(df['label_prom'])
    label_ss = list(df['label_ss'])
    label_polya = list(df['label_polya'])

    return sequence, label_prom, label_ss, label_polya

import torch
def preprocessing(data, tokenizer):
    """
    Preprocessing for pretrained BERT.
    @param  data (string): string containing kmers separated by spaces.
    @param  tokenizer (Tokenizer): tokenizer initialized from pretrained values.
    @return input_ids (torch.Tensor): tensor of token ids to be fed to model.
    @return attention_masks (torch.Tensor): tensor of indices (a bunch of 'indexes') specifiying which token needs to be attended by model.
    """
    input_ids = []
    attention_masks = []

    _count = 0
    _len_data = len(data)
    for sequence in data:
        """
        Sequence is 512 characters long.
        """
        _count += 1
        if _count < _len_data:
            print("Seq length = {} [{}/{}]".format(len(sequence.split(' ')), _count, _len_data), end='\r')
        else:
            print("Seq length = {} [{}/{}]".format(len(sequence.split(' ')), _count, _len_data))
        encoded_sent = tokenizer.encode_plus(
            text=sequence,
            padding='max_length',
            return_attention_mask=True
        )
        input_ids.append(encoded_sent.get('input_ids'))
        attention_masks.append(encoded_sent.get('attention_mask'))

    # Convert input_ids and attention_masks to tensor.
    input_ids = torch.tensor(input_ids)
    attention_masks = torch.tensor(attention_masks)

    return input_ids, attention_masks

"""
Initialize tokenizer using BertTokenizer with pretrained weights from DNABert.
"""
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('./pretrained/3-new-12w-0')

In [4]:
"""
Split dataset into two parts: train and validation.
"""
from data_dir import workspace_dir, dataset_full_dir
from data_preparation import split_and_store_csv
_src_csv = "{}/train.csv".format(dataset_full_dir)
_fractions = [0.9, 0.1]
_store_paths = [
    "{}/{}".format(workspace_dir, 'train.csv'),
    "{}/{}".format(workspace_dir, 'validation.csv'),
]
print("Splitting source {}: {}".format(_src_csv, split_and_store_csv(_src_csv, fractions=_fractions, store_paths=_store_paths)))

Splitting and storing split to ./workspace/train.csv
Splitting and storing split to ./workspace/validation.csv
Splitting source ./dataset/full/train.csv: True


In [4]:
import torch
from torch.utils.data import TensorDataset, DataLoader, RandomSampler
from data_dir import workspace_dir

train_seq, train_label_prom, train_label_ss, train_label_polya = get_sequences('{}/train.csv'.format(workspace_dir), n_sample=500000)
validation_seq, val_label_prom, val_label_ss, val_label_polya = get_sequences('{}/validation.csv'.format(workspace_dir), n_sample=100)

"""
Create dataloader.
"""
BATCH_SIZE = 2
EPOCH_SIZE = 4

_device = torch.device('cuda:0')
train_label_prom = torch.tensor(train_label_prom, device=_device)
train_label_ss = torch.tensor(train_label_ss, device=_device)
train_label_polya = torch.tensor(train_label_polya, device=_device)

train_inputs_ids, train_masks = preprocessing(train_seq, tokenizer)
train_data = TensorDataset(train_inputs_ids, train_masks, train_label_prom, train_label_ss, train_label_polya)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=BATCH_SIZE)

val_label_prom = torch.tensor(val_label_prom, device=_device)
val_label_ss = torch.tensor(val_label_ss, device=_device)
val_label_polya = torch.tensor(val_label_polya, device=_device)

val_input_ids, val_masks = preprocessing(validation_seq, tokenizer)
val_data = TensorDataset(val_input_ids, val_masks, val_label_prom, val_label_ss, val_label_polya)
val_sampler = RandomSampler(val_data)
val_dataloader = DataLoader(val_data, sampler=val_sampler, batch_size=BATCH_SIZE)

print('# of training data: {}'.format(len(train_seq)))  
print('# of training data: {}'.format(len(validation_seq)))

Seq length = 510 [500000/500000]
Seq length = 510 [100/100]
# of training data: 500000
# of training data: 100


In [1]:
from transformers import AdamW, get_linear_schedule_with_warmup
from torch.nn import CrossEntropyLoss
import numpy as np

from multitask_learning import PolyAHead, PromoterHead, SpliceSiteHead, MTModel
from transformers import BertForMaskedLM
from data_dir import pretrained_3kmer_dir

polya_head = PolyAHead()
promoter_head = PromoterHead()
splice_head = SpliceSiteHead()

dnabert_3_pretrained = pretrained_3kmer_dir
shared_parameter = BertForMaskedLM.from_pretrained(dnabert_3_pretrained).bert

model = MTModel(shared_parameters=shared_parameter, promoter_head=promoter_head, polya_head=polya_head, splice_site_head=splice_head)
optimizer = AdamW(model.parameters(), lr=5e-5, eps=1e-8)
loss_fn = CrossEntropyLoss()

c:\.virtualenv\sequence-processing-py39\lib\site-packages\transformers\optimization.py:306: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use thePyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(


In [139]:
import torch
import datetime
import os
from data_preparation import kmer

_now = datetime.datetime.now()

_log_file = os.path.join('logs', 'notebooks', '2022-02.24.csv')
os.makedirs(_log_file, exist_ok=True)

seqs = ["ATGC" * 128, "GATC" * 128, "CCAT" * 128]
seqs = [' '.join(kmer(s, 3)) for s in seqs]
prom_labels = [1, 0, 0]
ss_labels = [0, 1, 0]
polya_labels = [0, 0, 1]

def _format_prom_label(label):
    return [label]

def _format_other_label(label):
    return label

"""
Initialize BERT tokenizer.
"""
from transformers import BertTokenizer
from data_dir import pretrained_3kmer_dir
import torch
tokenizer = BertTokenizer.from_pretrained(pretrained_3kmer_dir)

arr_input_ids = []
arr_attention_mask = []
arr_prom_label = []
arr_ss_label = []
arr_polya_label = []
for i in range(len(seqs)):
    s = seqs[i]
    prom = prom_labels[i]
    ss = ss_labels[i]
    polya = polya_labels[i]

    encoded = tokenizer.encode_plus(text=s, padding="max_length", return_attention_mask=True)
    arr_input_ids.append(encoded.get('input_ids'))
    arr_attention_mask.append(encoded.get('attention_mask'))
    arr_prom_label.append(_format_prom_label(prom))
    arr_ss_label.append(_format_other_label(ss))
    arr_polya_label.append(_format_other_label(polya))
#endfor
arr_input_ids = torch.tensor(arr_input_ids)
arr_attention_mask = torch.tensor(arr_attention_mask)
prom_labels = torch.tensor(arr_prom_label)
ss_labels = torch.tensor(arr_ss_label)
polya_labels = torch.tensor(arr_polya_label)

from torch.utils.data import DataLoader, TensorDataset
dataset = TensorDataset(arr_input_ids, arr_attention_mask, prom_labels, ss_labels, polya_labels)
dataloader = DataLoader(dataset, batch_size=1)

In [140]:
prom_labels[0]

tensor([1])

In [145]:
from tqdm import tqdm
from torch.nn import CrossEntropyLoss, BCELoss

crossentropy_function = CrossEntropyLoss()
binary_crossentropy_function = BCELoss()
model.zero_grad()
for step, batch in tqdm(enumerate(dataloader), total=len(dataloader)):
    in_ids, attn_mask, label_prom, label_ss, label_polya = tuple(t for t in batch)
    output = model(in_ids, attn_mask)
    pred_prom = output['prom']
    pred_ss = output['ss']
    pred_polya = output['polya']    
    loss_prom = binary_crossentropy_function(pred_prom, label_prom.float())
    loss_ss = crossentropy_function(pred_ss, label_ss)
    loss_polya = crossentropy_function(pred_polya, label_polya)
    print(pred_prom, label_prom, loss_prom)
    print(pred_ss, label_ss, loss_ss)
    print(pred_polya, label_polya, loss_polya)
    sum_loss = loss_prom + loss_ss + loss_polya
    print(sum_loss, sum_loss/3)



 33%|███▎      | 1/3 [00:00<00:01,  1.02it/s]

tensor([[0.5452]], grad_fn=<SigmoidBackward0>) tensor([[1]]) tensor(0.6066, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[0.4535, 0.5465]], grad_fn=<SoftmaxBackward0>) tensor([0]) tensor(0.7408, grad_fn=<NllLossBackward0>)
tensor([[0.6232, 0.3768]], grad_fn=<SoftmaxBackward0>) tensor([0]) tensor(0.5775, grad_fn=<NllLossBackward0>)
tensor(1.9249, grad_fn=<AddBackward0>) tensor(0.6416, grad_fn=<DivBackward0>)


 67%|██████▋   | 2/3 [00:02<00:01,  1.01s/it]

tensor([[0.5974]], grad_fn=<SigmoidBackward0>) tensor([[0]]) tensor(0.9098, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[0.4219, 0.5781]], grad_fn=<SoftmaxBackward0>) tensor([1]) tensor(0.6181, grad_fn=<NllLossBackward0>)
tensor([[0.5926, 0.4074]], grad_fn=<SoftmaxBackward0>) tensor([0]) tensor(0.6048, grad_fn=<NllLossBackward0>)
tensor(2.1327, grad_fn=<AddBackward0>) tensor(0.7109, grad_fn=<DivBackward0>)


100%|██████████| 3/3 [00:03<00:00,  1.00s/it]

tensor([[0.5034]], grad_fn=<SigmoidBackward0>) tensor([[0]]) tensor(0.7001, grad_fn=<BinaryCrossEntropyBackward0>)
tensor([[0.4662, 0.5338]], grad_fn=<SoftmaxBackward0>) tensor([0]) tensor(0.7276, grad_fn=<NllLossBackward0>)
tensor([[0.6131, 0.3869]], grad_fn=<SoftmaxBackward0>) tensor([1]) tensor(0.8126, grad_fn=<NllLossBackward0>)
tensor(2.2402, grad_fn=<AddBackward0>) tensor(0.7467, grad_fn=<DivBackward0>)


In [127]:
from torch.nn import BCELoss, CrossEntropyLoss
from torch import tensor
prom_pred = tensor([[0.2]])
prom_target = tensor([[0.]])
other_pred = tensor([[0.1, 1.5]])
other_target = tensor([0])
bce = BCELoss()
cross = CrossEntropyLoss()
print(bce(prom_pred, prom_target))
print(cross(other_pred, other_target))

tensor(0.2231)
tensor(1.6204)


In [ ]:
import torch
import datetime
import os
from data_preparation import kmer
from transformers import BertTokenizer
from data_dir import pretrained_3kmer_dir

_now = datetime.datetime.now()

_log_file = os.path.join('logs', 'notebooks', '2022-02.24.csv')
os.makedirs(_log_file, exist_ok=True)

seqs = ["ATGC" * 128, "GATC" * 128, "CCAT" * 128]
seqs = [' '.join(kmer(s, 3)) for s in seqs]
prom_labels = [1, 0, 0]
ss_labels = [0, 1, 0]
polya_labels = [0, 0, 1]

tokenizer = BertTokenizer.from_pretrained(pretrained_3kmer_dir)
encoded = tokenizer(seqs[0], seqs[1])
print(encoded)
print(tokenizer.convert_ids_to_tokens(encoded['input_ids']))

In [ ]:
from multitask_learning import evaluate, init_model_mtl
from data_dir import pretrained_3kmer_dir

model = init_model_mtl(pretrained_3kmer_dir, 'cuda:0')
avg_prom_acc, avg_ss_acc, avg_polya_acc, avg_prom_loss, avg_ss_loss, avg_polya_loss = evaluate(model, )